config/routes.rb
SurfEd::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    resources :users, only: [:index, :edit ,:update, :show]
  end
  resources :invite, except: [:destroy, :edit, :update, :show]
  

  resources :topics do 
    new do
      post :upload
      get  :save_video
    end
    member do
      post :vote_up
    end
  end
  
  resources :answers do
    member do
      post :vote_up
      post :vote_down
    end
  end
  root to: 'home#index'

  resources :searches, only: [:create]

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  acts_as_voteable
  
  belongs_to :user
  has_many :answers, :dependent => :destroy

  has_and_belongs_to_many :fans, :class_name => "User"
  attr_accessible :question, :yt_video_id, :is_complete, :added_video, :user_id

  validates :question, presence: true
  validates :question, length: { minimum: 5 }


  scope :completes,   where(:is_complete => true)
  scope :incompletes, where(:is_complete => false)

  def self.yt_session
    @yt_session ||= YouTubeIt::Client.new(:username => ENV["YOUTUBE_IT_USERNAME"] , :password => ENV["YOUTUBE_IT_PASSWORD"] , :dev_key => ENV["YOUTUBE_IT_DEV_KEY"])    
  end

  def self.delete_video(video)
    yt_session.video_delete(video.yt_video_id)
    video.destroy
      rescue
        video.destroy
  end

  def self.update_video(topic, params)
    if topic.added_video
      yt_session.video_update(topic.yt_video_id, video_options(params))
      topic.update_attributes(params)
    else
      topic.update_attributes(params)
    end
  end

  def self.token_form(params, nexturl)
    yt_session.upload_token(video_options(params), nexturl)
  end

  def self.delete_incomplete_videos
    self.incompletes.map{|r| r.destroy}
  end


  private
    def self.video_options(params)
      opts = {:title => params[:question],
             :description => "A Surf.ed video",
             :category => "Sports",
             :keywords => ["surfing"]}
      params[:is_unpublished] == "1" ? opts.merge(:private => "true") : opts
    end
      
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  load_and_authorize_resource :except => [:save_video]

  def index
    @topics = Topic.all 
    @topics_suggest = Topic.fuzzy_search params[:query]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics_suggest.pluck(:question) }
    end
  end

  def upload
    video = params[:topic][:added_video]
    @topic = Topic.new(params[:topic])
    @topic.user = current_user
    @topic.save
    if video == "1"
      if @topic.save
         @upload_info = Topic.token_form(params[:topic], save_video_new_topic_url(:topic_id => @topic.id))
      else
        respond_to do |format|
          format.html { render "/topics/new" }
        end
      end
    else 
      @topic.update_attributes(:is_complete => true)
      @topic.save
      redirect_to @topic, :notice => "Question has been created"
    end

  end

  def save_video
    @topic = Topic.find(params[:topic_id])

    if params[:status].to_i == 200
      @topic.update_attributes(:yt_video_id => params[:id].to_s, :is_complete => true)
      Topic.delete_incomplete_videos
    else
      Topic.delete_video(@topic)
    end
    redirect_to @topic, :notice => "video successfully uploaded"
  end

  def show
    @answer = Answer.new
    @answers = @topic.answers.paginate(page: params[:answer_page], per_page: 2).plusminus_tally.order('plusminus_tally DESC').all
  end

  def edit
  end
  
  def update
    @topic     = Topic.find(params[:id])
    @result    = Topic.update_video(@topic, params[:topic])
    respond_to do |format|
      format.html do
        if @result
          redirect_to @topic, :notice => "Question successfully updated"
        else
          respond_to do |format|
            format.html { render "/videos/_edit" }
          end
        end
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    User.update_score(current_user)
    if Topic.delete_video(@topic)
      flash[:notice] = "Question successfully deleted"
    else
      flash[:error] = "Question unsuccessfully deleted"
    end
    redirect_to root_path
  end

  def vote_up

    @topic = Topic.find params[:id]
    current_user.vote_for(@topic)
    @topic.score += 1
    @topic.fans << current_user

    User.invitaion_update(@topic.user)
    User.update_score(@topic.user)

    @topic.save

    redirect_to @topic

  end

end

app/views/topics/_answer.html.haml
- @answers.each do |answer|
  .votes
    - if can? :vote_up, :vote_down, answer
      %br
      - if current_user.voted_against?(answer)
        .vote-thumb=image_tag "065.png"
      - elsif current_user.voted_for?(answer)
        .vote-thumb=image_tag "064.png"
      - else 
        .vote-thumb
          = link_to vote_up_answer_path(answer), :method => :post, class: "form-button" do
            =image_tag "064.png"
        .vote-thumb
          = link_to vote_down_answer_path(answer), :method => :post, class: "form-button" do
            =image_tag "065.png"
  %p
    =link_to answer.user do
      Answer Given by 
      = answer.user.name
  .answer-topic-show
    %p= answer.answer
  - if !!answer.votes
    %p
      Score : 
      = (answer.votes_for - answer.votes_against)
  %br
  - if can? :edit, answer
    = link_to 'Edit Answer', edit_answer_path(answer)
  - if can? :destroy, answer
    = link_to 'Delete Answer', answer, method: :delete
  %hr

= will_paginate @answers, param_name: "answer_page", :page_links => false, previous_label: "PREVIOUS", next_label: "NEXT"

app/views/topics/edit.html.haml
%ul.errors
  - @topic.errors.full_messages.each do |error|
    %li= error
.devise-form
  %h2 Edit question

  = form_for @topic, :url => topic_path(@topic) do |f|
    = f.text_field :question, placeholder: "Whats your question ?"
    .form-button= f.submit "Save"

app/views/topics/index.html.haml
%h3 Questions

%ul
  - @topics.each do |topic|
    %li
      =link_to topic.question, topic
      / %p By #{topic.user.name} 

app/views/topics/new.html.haml
.header-margin
  %ul.errors
    - @topic.errors.full_messages.each do |error|
      %li= error
  .devise-form
    %h2 Ask a Question

    = form_for @topic, :url => upload_new_topic_path do |f|
      = f.text_field :question, placeholder: "Whats your question ?",autocomplete: :off, autofocus: true;
  
      / %h3 Do You want to Add Video ?
      .checkbox.form-button
        .checkbox-box
          .checkbox-value= f.check_box :added_video, {id: "boom-box"}
          %p.checkbox-no Click to Add Video
          %p.checkbox-yes Now Choose Next
      .actions.form-button.submit
        .checkbox-no
          = f.submit "Submit Question"
        .checkbox-yes
          = f.submit "Next"

app/views/topics/show.html.haml
:javascript
  var topic = JSON.parse('#{@topic.to_json}');

.question-side-bar.cf
  .question-top-bar
    .star-location
      - if can? :vote_up, @topic
        - if current_user.voted_for?(@topic)
          .starred-image=image_tag 'starred.png'
        -else
          = link_to vote_up_topic_path(@topic), :method => :post, class: "form-button",  title: "STAR QUESTION", id: "star_question_icon", "data-placement" => "top" do
            .star-image=image_tag 'star.png'

    .user-link
      %h4
        =link_to @topic.user, title: "VIEW USER PROFILE", id: "topic_user_profile_icon", "data-placement" => "top"  do
          .avatar-show=image_tag avatar_url(@topic.user)
          = @topic.user.name
    
    - if can? :edit, @topic
      .links-user
        = link_to "Edit", edit_topic_path(@topic)
        |
        = link_to "Delete", topic_path(@topic), :method => "delete"

.question-content.cf
  %h2= "#{@topic.user.name}'s Question"
  %h3= @topic.question
  .question-video.cf
    
    - if @topic.yt_video_id
      #player

  - if @topic.answers.plusminus_tally.first
    .top-answer.cf
      - top = @topic.answers.plusminus_tally.order('plusminus_tally DESC').first
      %p Top Answer 
      %h4= top.answer

      .votes
        - if can? :vote_up, :vote_down, top
          %br
          - if current_user.voted_against?(top)
            .vote-thumb=image_tag "065.png"
          - elsif current_user.voted_for?(top)
            .vote-thumb=image_tag "064.png"
          - else 
            .vote-thumb
              = link_to vote_up_answer_path(top), :method => :post, class: "form-button" do
                =image_tag "064.png"
            .vote-thumb
              = link_to vote_down_answer_path(top), :method => :post, class: "form-button" do
                =image_tag "065.png"


  .other-answers.cf
    .answer-form-topics
      - if can? :create, @answer
        %h2 Add a Answer
        / %ul.errors
        /   - @answer.errors.full_messages.each do |error|
        /     %li= error
        .devise-form
          = form_for(@answer) do |f|
            = hidden_field_tag :topic_id, @topic.id
            = f.text_field :answer, placeholder: "Write answer here...", required: true
            %br/
            .comments-form-button
              .form-button= f.submit "Submit Answer"
    .answer-paginated
      =render "answer"

app/views/topics/show.js.erb
;$(".answer-paginated").html("<%= escape_javascript(render("answer")) %>");

app/views/topics/upload.html.haml
.devise-form
  %h2 Choose and Upload Video

  = form_tag @upload_info[:url], multipart: true do
    = hidden_field_tag :token, @upload_info[:token]
    .file-upload.btn
      .p Click to choose video
      = file_field_tag :file, {class: "uploadBtn upload", required: true  }

    .form-button= submit_tag "Upload and submit"