config/routes.rb
SurfEd::Application.routes.draw do
  devise_for :users

  devise_scope :user do
    resources :users, only: [:index, :edit ,:update, :show]
  end
  resources :invite, except: [:destroy, :edit, :update, :show]
  

  resources :topics do 
    new do
      post :upload
      get  :save_video
    end
    member do
      post :vote_up
    end
  end
  
  resources :answers do
    member do
      post :vote_up
      post :vote_down
    end
  end
  root to: 'home#index'

  resources :searches, only: [:create]

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SurfEd
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    %link{href: "http://fonts.googleapis.com/css?family=Maven+Pro:400,500,700,900", rel: "stylesheet", type: "text/css"}/
    %script type="text/javascript" src="jquery-2.0.3.js"

    = csrf_meta_tags
  %body
    .surf-container
      .site-header.cf
        %h1#logo-header=link_to "Surf.Ed", root_path
        .user-login
          -if can? :create, Topic
            .icon
              = link_to new_topic_path, title: "ASK QUESTION", id: "new_question_icon", "data-placement" => "bottom" do
                =image_tag 'question.png'
          
          .icon    
            %a.search=image_tag 'search.png', options = {title: "SEARCH", id: "search_question_icon", "data-placement" => "bottom" }

          - if user_signed_in?            
            .icon
              = link_to destroy_user_session_path, method: :delete, title: "LOG OUT", id: "log_out_icon", "data-placement" => "bottom"  do
                =image_tag 'on-off.png'

            .avatar-main.icon
              = link_to current_user,  title: "USER PROFILE", id: "user_profile_icon", "data-placement" => "bottom" do
                = image_tag avatar_url(current_user)      

          - else
            .icon
              = link_to 'LOGIN', new_user_session_path
          
          
      .overlay
        %span.close.cf x
        %h1.cf SURF.ED
        %h1.cf SEARCH
        = form_tag searches_path do
          .input-box.col-md-6
            = text_field_tag :query, nil, :class => 'search-input input-box', :placeholder => 'search...', :autocomplete =>"off", :autofocus => true
            .hide-me= submit_tag "submit"
      .head.side-bar-nav      
        - flash.each do |name, msg|
          = content_tag :div, msg, :id => "flash_#{name}"
        
      .main
        .inner-container
          = yield
          
      / .footer
      
      /   SURF.ED Footer stuff